SET SERVEROUTPUT ON;

CREATE TABLE receipts (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_name VARCHAR2(100),
    city VARCHAR2(100),
    receipt_date DATE,
    total NUMBER(10, 2)
);

CREATE TABLE receipt_items (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_id NUMBER,
    item_name VARCHAR2(200),
    category VARCHAR2(100),
    FOREIGN KEY (receipt_id) REFERENCES receipts(id)
);

select * from receipts;
select * from receipt_items;

SELECT 
    r.id AS receipt_id,
    r.store_name,
    r.city,
    r.receipt_date,
    r.total,
    i.id AS item_id,
    i.item_name,
    i.category
FROM 
    receipts r
JOIN 
    receipt_items i ON r.id = i.receipt_id;


drop table receipts;
drop table receipt_items;